# Linear algebra in Python with NumPy

In this lab, you will have the opportunity to remember some basic concepts about linear algebra and how to use them in Python.

Numpy is one of the most used libraries in Python for arrays manipulation. It adds to Python a set of functions that allows us to operate on large multidimensional arrays with just a few lines. So forget about writing nested loops for adding matrices! With NumPy, this is as simple as adding numbers.

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt


# Defining lists and numpy arrays


In [2]:
alist = [1,2,3,4,5]

narray = np.array([1,2,3,4])

In [4]:
print(alist)
print(narray)

print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


# Algebraic operators on Numpy arrays vs python list

In [7]:
# adding list and array

print(narray + narray) # adding the elements
print(alist + alist) # this concatenates the list

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [10]:
for i in alist:
    i += i 
    print(i)

2
4
6
8
10


**Note** Be aware of the difference because, within the same function, both types of arrays can appear. Numpy arrays are designed for numerical and matrix operations, while lists are for more general purposes.
* To add the element of a list we need a loop as shown above

# Matrix or Array of Arrays

In linear algebra, a matrix is a structure composed of n rows by m columns. That means each row must have the same number of columns. With NumPy, we have two ways to create a matrix:
* Creating an array of arrays using `np.array` (recommended). 
* Creating a matrix using `np.matrix` (still available but might be removed soon).

NumPy arrays or lists can be used to initialize a matrix, but the resulting matrix will be composed of NumPy arrays only.

In [15]:
matrix1 = np.array([narray, narray, narray]) # with np.array
matrix2 = np.array([alist, alist, alist]) # with list
matrix3 =  np.array([narray, [1,1,1,1], narray]) # matrix  initialization with both type
    
    
print(matrix1)
print('\n',matrix2)
print('\n',matrix3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]

 [[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


In [16]:
# Examples

okmatrix = np.array([[1,2], [3,4]])
print(okmatrix)
print('\n', okmatrix * 2)

[[1 2]
 [3 4]]

 [[2 4]
 [6 8]]


In [19]:
# Example 2

badmatrix = np.array([[1,2], [3,4], [5,6,7]])
print(badmatrix)
print('\n', badmatrix * 2)

[list([1, 2]) list([3, 4]) list([5, 6, 7])]

 [list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


# Scaling and Translating matrices

Operations can be performed between arrays and arrays or between arrays and scalars.

In [20]:
# scale by 2 and translate 1 unit the matrix

result = okmatrix * 2 + 1

print(result)

[[3 5]
 [7 9]]


In [23]:
#adding two sum compatible matrices

result1 = okmatrix + okmatrix
print(result1)

# subtract two sum compatible matrices
result2 = okmatrix - okmatrix
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


In [24]:
#multiply

result = okmatrix * okmatrix

print(result)

[[ 1  4]
 [ 9 16]]


# Transpose a Matrix

In linear algebra, the transpose of a matrix is an operator that flips a matrix over its diagonal, i.e., the transpose operator switches the row and column indices of the matrix producing another matrix. If the original matrix dimension is n by m, the resulting transposed matrix will be m by n.

**T** denotes the transpose operations with NumPy matrices.

In [26]:
matrix4 = np.array([[1,2], [3,4], [5,7]]) # 3X2 matrix
print('Original matrix 3 X 2')
print(matrix4)
    
print('Transposed matrix 2 X 3')
print(matrix4.T)

Original matrix 3 X 2
[[1 2]
 [3 4]
 [5 7]]
Transposed matrix 2 X 3
[[1 3 5]
 [2 4 7]]


In [27]:
np.transpose(matrix4)

array([[1, 3, 5],
       [2, 4, 7]])

In [28]:
matrix4.transpose()

array([[1, 3, 5],
       [2, 4, 7]])

In [29]:
nparray = np.array([1,2,3,4,5])

print('Original array')

print(nparray)
print('Transposed array')
print(narray.T)

Original array
[1 2 3 4 5]
Transposed array
[1 2 3 4]


# Double bracket can help it

In [31]:
nparray = np.array([[1, 2, 3, 4]]) # Define a 1 x 4 matrix. Note the 2 level of square brackets
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]


## Get the norm of a nparray or matrix

In linear algebra, the norm of an n-dimensional vector $\vec a$   is defined as:

$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2}$$

Calculating the norm of vector or even of a matrix is a general operation when dealing with data. Numpy has a set of functions for linear algebra in the subpackage **linalg**, including the **norm** function. Let us see how to get the norm a given array or matrix:

In [34]:
nparray1 = np.array([1,2,3,4])
norm1 = np.linalg.norm(nparray1)

print('norm1',norm1)

nparray2 = np.array([[1,2], [3, 4]])
norm2 = np.linalg.norm(nparray2)

print('norm2', norm2)

norm1 5.477225575051661
norm2 5.477225575051661


# Norm by row or by columns


In [38]:
nparray2 = np.array([[1,2],[2,2] , [3, 3]])
normByCols = np.linalg.norm(nparray2, axis =0) # norm of column
normByRows = np.linalg.norm(nparray2, axis =1) # norm of row
print(nparray2)
print('By columns',normByCols)
print('By Row',normByRows)

[[1 2]
 [2 2]
 [3 3]]
By columns [3.74165739 4.12310563]
By Row [2.23606798 2.82842712 4.24264069]


## The dot product between arrays: All the flavors

The dot product or scalar product or inner product between two vectors $\vec a$ and $\vec b$ of the same size is defined as:
$$\vec a \cdot \vec b = \sum_{i=1}^{n} a_i b_i$$

The dot product takes two vectors and returns a single number.

In [43]:
nparray1 = np.array([0, 1, 2, 3])
nparray2 = np.array([4,5,6,7])

flavor1 = np.dot(nparray1, nparray2) # recommended way
print(flavor1)

flavor2 = np.sum(nparray1 * nparray2) # ok way
print(flavor2)

flavor3 = nparray1 @ nparray2 # Geek2 way
print(flavor3)

# Noob way,, mever do this
flavor4 = 0 
for a, b in zip(nparray1, nparray2):
    flavor4 += a*b
print(flavor4)

38
38
38
38


**Note** We strongly recommend using np.dot, since it is the only method that accepts arrays and lists without problems


In [44]:
norm1 = np.dot(np.array([1,2]), np.array([3,4])) # Dot product of nparray
norm2 = np.dot([1,2], [3,4]) # Dot product on python lists

print(norm1, '=', norm2)

11 = 11


Finally, note that the norm is the square root of the dot product of the vector with itself. That gives many options to write that function:

$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2} = \sqrt {a \cdot a}$$

## Sums by rows or columns

Another general operation performed on matrices is the sum by rows or columns.
Just as we did for the function norm, the **axis** parameter controls the form of the operation:
* **axis=0** means to sum the elements of each column together. 
* **axis=1** means to sum the elements of each row together.

In [50]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) # Define a 3 x 2 matrix. 

sumByCols = np.sum(nparray2, axis=0) # Get the sum for each column. Returns 2 elements
sumByRows = np.sum(nparray2, axis=1) # get the sum for each row. Returns 3 elements
print(np.sum(nparray2))
print('Sum by columns: ')
print(sumByCols)
print('Sum by rows:')
print(sumByRows)


0
Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]


## Get the mean by rows or columns

As with the sums, one can get the **mean** by rows or columns using the **axis** parameter. Just remember that the mean is the sum of the elements divided by the length of the vector
$$ mean(\vec a) = \frac {{\sum_{i=1}^{n} a_i }}{n}$$

In [53]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) # Define a 3 x 2 matrix. Chosen to be a matrix with 0 mean

mean = np.mean(nparray2) # Get the mean for the whole matrix
meanByCols = np.mean(nparray2, axis=0) # Get the mean for each column. Returns 2 elements
meanByRows = np.mean(nparray2, axis=1) # get the mean for each row. Returns 3 elements
print(nparray2)
print('Matrix mean: ')
print(mean)
print('Mean by columns: ')
print(meanByCols)
print('Mean by rows:')
print(meanByRows)

[[ 1 -1]
 [ 2 -2]
 [ 3 -3]]
Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]


## Center the columns of a matrix

Centering the attributes of a data matrix is another essential preprocessing step. Centering a matrix means to remove the column mean to each element inside the column. The sum by columns of a centered matrix is always 0.

With NumPy, this process is as simple as this:

In [56]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2 - np.mean(nparray2, axis =0)

print('Original matrix')
print(nparray2)
print('Centered by column matrix')
print(nparrayCentered)

print('New mean by column')
print(nparrayCentered.mean(axis=0))

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by column matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]


#  row centering.
In such cases, consider transposing the matrix, centering by columns, and then transpose back the result.

In [57]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2.T - np.mean(nparray2, axis=1) # Remove the mean for each row
nparrayCentered = nparrayCentered.T # Transpose back the result

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by rows')
print(nparrayCentered.mean(axis=1))

Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by columns matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]


In [59]:
# some operatons can be performed using static fucntions like np.sum() or np.mean() 
# or the inner function of the array

In [60]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

mean1 = np.mean(nparray2) # Static way
mean2 = nparray2.mean()   # Dinamic way

print(mean1, ' == ', mean2)

3.0  ==  3.0


**NOTE** Even if they are equivalent, It is highly recommended to use the **static way that is np.mean()**